### ISSUE TITLE
Flag type GLASS not considerate like a coloredBlock

### ISSUE THREAD

**Issue by Oruss7** [Eredrim/pvparena#86] opened 2021-02-20 17:08 UTC
People are just confused between WHITE_STAINED_GLASS and GLASS.
GLASS doesn't seems to be a colorable block as Stained Glass.

2 options: 

- Dynamically replace GLASS by WHITE_STAINED_GLASS
- Display a nice error message (specially for the Domination goal) when setting flag and/or flagtype

**Comment by Eredrim** [comment] 2021-02-20 23:57
The problem is domination goal doesn't have flagtype setting. Any flag types can be used and blended if they all are colorable blocks (if the list defined in documentation).

So, this leads to the real problem: the lack of standardization. In PVPArena, there are four ways to select coordinates (player position, eye position, block clicking and block clicking with selection). 
So those processes have to be simplified and help has to be improved (with errors messages in this case).

**Comment by Eredrim** [comment] 2023-03-19 23:18
Fixed in 2.0 dev preview. Colorable blocks are now automatically deducted from the register block.

**Closed by Eredrim** 2023-03-19 23:18 UTC
Labels: enhancement
