### ISSUE TITLE
Spectate and FlySpectate modules have weird end-of-game behaviors

### ISSUE THREAD

**Issue by Harrison-B** [Eredrim/pvparena#97] opened 2021-04-07 19:13 UTC
I'd love to use the FlySpectate or Spectate modules as I have a really big arena, however I think I ran into a bug with both of them. 

When a player left a game and came back in spectate mode using /pa [arena] spectate, they were correctly sent to the spectator spawn and put into the respective spectate mode for the module (flight and invis, or 1.8 spectator). However when the player used "/pa leave" or the match ended, they were not teleported out of the arena, and instead were just dropped to the ground, with their survival inventories from before they joined the arena. 

"/pa leave" seems to work fine if the player is currently playing the game.

**Comment by Eredrim** [comment] 2021-04-15 20:18
Hello,

after several tests, I'm unable to reproduce your issue with PVPArena 1.15.1 (and up-to-date modules pack).

-----
My test scenarios (tried with FlySpectate and Spectate):
3 players: p1, p2 & p3

* p1 & p2 join the arena
* p3 spectates
* p1 loses => p1 teleported in spec
* [end countdown]
* p1, p2 and p3 are removed from the arena and teleported to exit  
~
* p1 & p2 join the arena
* p3 spectates
* p3 types /pa leave
* p3 is removed from the arena and teleported to exit  
~
* p1 & p2 join the arena
* p3 spectates
* p3 escapes from WATCH region
* p3 is removed from the arena and teleported to exit

My test environment:
- PaperMC 1.16.5
- PVPArena 1.5.1
- PVPArena Module Pack 1.15.1
- Plugins: blocklocker, CommandHook, EssentialsX, Multiverse Core, Multiverse Portals, PerWorldInventories, Residence, Vault, WorldEdit, WorldGuard

**Comment by Eredrim** [comment] 2021-05-17 21:23
I close this issue. I let you reopen it if needed.

**Closed by Eredrim** 2021-05-17 21:23 UTC
Labels: bug, can't reproduce
